services:
  - type: web
    name: crm-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        value: https://crm-backend.onrender.com/api
